import {Inter} from "next/font/google";
import {NextIntlClientProvider} from "next-intl";
import { getMessages } from "next-intl/server";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";
import Modals from "@/modals";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params: {locale}}) {
  const messages = await getMessages();
  return (
      <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        <Header/>
        <main className="main">
          {children}
        </main>
        <Footer/>
        <Modals />
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
